//
//  DummyData.swift
//  Techome
//
//  Created by Yeongwoo Kim on 2022/06/09.
//

import Foundation

let dummyBeverages: [Beverage] = [
    Beverage(name: "스타벅스 돌체 라떼",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 150, defaultShotCount: 2),
                        SizeInfo(name: "Grande", caffeineAmount: 225, defaultShotCount: 3),
                        SizeInfo(name: "Venti", caffeineAmount: 300, defaultShotCount: 4)]),
    Beverage(name: "카페 모카",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 95, defaultShotCount: 1),
                        SizeInfo(name: "Grande", caffeineAmount: 175, defaultShotCount: 2),
                        SizeInfo(name: "Venti", caffeineAmount: 180, defaultShotCount: 2)]),
    Beverage(name: "카페 아메리카노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 150, defaultShotCount: 2),
                        SizeInfo(name: "Grande", caffeineAmount: 225, defaultShotCount: 3),
                        SizeInfo(name: "Venti", caffeineAmount: 300, defaultShotCount: 4)]),
    Beverage(name: "카페 라떼",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 75, defaultShotCount: 1),
                        SizeInfo(name: "Grande", caffeineAmount: 150, defaultShotCount: 2),
                        SizeInfo(name: "Venti", caffeineAmount: 150, defaultShotCount: 2)]),
    Beverage(name: "카푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 75, defaultShotCount: 1),
                        SizeInfo(name: "Grande", caffeineAmount: 150, defaultShotCount: 2),
                        SizeInfo(name: "Venti", caffeineAmount: 150, defaultShotCount: 2)]),
    Beverage(name: "카라멜 마끼아또",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 75, defaultShotCount: 1),
                        SizeInfo(name: "Grande", caffeineAmount: 150, defaultShotCount: 2),
                        SizeInfo(name: "Venti", caffeineAmount: 150, defaultShotCount: 2)]),
    Beverage(name: "화이트 초콜릿 모카",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 75, defaultShotCount: 1),
                        SizeInfo(name: "Grande", caffeineAmount: 150, defaultShotCount: 2),
                        SizeInfo(name: "Venti", caffeineAmount: 150, defaultShotCount: 2)]),
    Beverage(name: "더블 에스프레소 칩 프라푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 130, defaultShotCount: 2),
                        SizeInfo(name: "Grande", caffeineAmount: 130, defaultShotCount: 2),
                        SizeInfo(name: "Venti", caffeineAmount: 260, defaultShotCount: 4)]),
    Beverage(name: "제주 유기농 말차로 만든 크림 프라푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 60, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 90, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 120, defaultShotCount: 0)]),
    Beverage(name: "자바 칩 프라푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 100, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 130, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 180, defaultShotCount: 0)]),
    Beverage(name: "화이트 초콜릿 모카 프라푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 85, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 110, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 155, defaultShotCount: 0)]),
    Beverage(name: "모카 프라푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 90, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 115, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 165, defaultShotCount: 0)]),
    Beverage(name: "카라멜 프라푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 85, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 110, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 155, defaultShotCount: 0)]),
    Beverage(name: "에스프레소 프라푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 120, defaultShotCount: 1),
                        SizeInfo(name: "Grande", caffeineAmount: 155, defaultShotCount: 2),
                        SizeInfo(name: "Venti", caffeineAmount: 155, defaultShotCount: 2)]),
    Beverage(name: "제주 유기농 말차로 만든 라떼",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 60, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 90, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 120, defaultShotCount: 0)]),
    Beverage(name: "차이 티 라떼",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 70, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 95, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 115, defaultShotCount: 0)]),
    Beverage(name: "자몽 허니 블랙 티",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 70, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 95, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 150, defaultShotCount: 0)]),
    Beverage(name: "잉글리시 브렉퍼스트 티",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 70, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 150, defaultShotCount: 0)]),
    Beverage(name: "얼 그레이 티",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 70, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 120, defaultShotCount: 0)]),
    Beverage(name: "오늘의 커피",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 260, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 330, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 415, defaultShotCount: 0)]),
]
