//
//  DummyData.swift
//  Techome
//
//  Created by Yeongwoo Kim on 2022/06/09.
//

import Foundation

let dummyBeverages: [Beverage] = [
    Beverage(name: "스타벅스 돌체 라떼",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 150, defaultShotCount: 2),
                        SizeInfo(name: "Grande", caffeineAmount: 225, defaultShotCount: 3),
                        SizeInfo(name: "Venti", caffeineAmount: 300, defaultShotCount: 4)]),
    Beverage(name: "카페 모카",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 95, defaultShotCount: 1),
                        SizeInfo(name: "Grande", caffeineAmount: 175, defaultShotCount: 2),
                        SizeInfo(name: "Venti", caffeineAmount: 180, defaultShotCount: 2)]),
    Beverage(name: "카페 아메리카노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 150, defaultShotCount: 2),
                        SizeInfo(name: "Grande", caffeineAmount: 225, defaultShotCount: 3),
                        SizeInfo(name: "Venti", caffeineAmount: 300, defaultShotCount: 4)]),
    Beverage(name: "카페 라떼",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 75, defaultShotCount: 1),
                        SizeInfo(name: "Grande", caffeineAmount: 150, defaultShotCount: 2),
                        SizeInfo(name: "Venti", caffeineAmount: 150, defaultShotCount: 2)]),
    Beverage(name: "카푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 75, defaultShotCount: 1),
                        SizeInfo(name: "Grande", caffeineAmount: 150, defaultShotCount: 2),
                        SizeInfo(name: "Venti", caffeineAmount: 150, defaultShotCount: 2)]),
    Beverage(name: "카라멜 마끼아또",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 75, defaultShotCount: 1),
                        SizeInfo(name: "Grande", caffeineAmount: 150, defaultShotCount: 2),
                        SizeInfo(name: "Venti", caffeineAmount: 150, defaultShotCount: 2)]),
    Beverage(name: "화이트 초콜릿 모카",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 75, defaultShotCount: 1),
                        SizeInfo(name: "Grande", caffeineAmount: 150, defaultShotCount: 2),
                        SizeInfo(name: "Venti", caffeineAmount: 150, defaultShotCount: 2)]),
    Beverage(name: "더블 에스프레소 칩 프라푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 130, defaultShotCount: 2),
                        SizeInfo(name: "Grande", caffeineAmount: 130, defaultShotCount: 2),
                        SizeInfo(name: "Venti", caffeineAmount: 260, defaultShotCount: 4)]),
    Beverage(name: "제주 유기농 말차로 만든 크림 프라푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 60, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 90, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 120, defaultShotCount: 0)]),
    Beverage(name: "자바 칩 프라푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 100, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 130, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 180, defaultShotCount: 0)]),
    Beverage(name: "화이트 초콜릿 모카 프라푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 85, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 110, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 155, defaultShotCount: 0)]),
    Beverage(name: "모카 프라푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 90, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 115, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 165, defaultShotCount: 0)]),
    Beverage(name: "카라멜 프라푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 85, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 110, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 155, defaultShotCount: 0)]),
    Beverage(name: "에스프레소 프라푸치노",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 120, defaultShotCount: 1),
                        SizeInfo(name: "Grande", caffeineAmount: 155, defaultShotCount: 2),
                        SizeInfo(name: "Venti", caffeineAmount: 155, defaultShotCount: 2)]),
    Beverage(name: "제주 유기농 말차로 만든 라떼",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 60, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 90, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 120, defaultShotCount: 0)]),
    Beverage(name: "차이 티 라떼",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 70, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 95, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 115, defaultShotCount: 0)]),
    Beverage(name: "자몽 허니 블랙 티",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 70, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 95, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 150, defaultShotCount: 0)]),
    Beverage(name: "잉글리시 브렉퍼스트 티",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 70, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 150, defaultShotCount: 0)]),
    Beverage(name: "얼 그레이 티",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 70, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 120, defaultShotCount: 0)]),
    Beverage(name: "오늘의 커피",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 260, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 330, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 415, defaultShotCount: 0)]),
    Beverage(name: "오늘의 커피",
             franchise: Franchise.starbucks,
             sizeInfo: [SizeInfo(name: "Tall", caffeineAmount: 140, defaultShotCount: 0),
                        SizeInfo(name: "Grande", caffeineAmount: 190, defaultShotCount: 0),
                        SizeInfo(name: "Venti", caffeineAmount: 220, defaultShotCount: 0)]),
]

let dummyTwosomePlaceBeverages: [Beverage] = [
    Beverage(name: "스페니쉬 연유 카페라떼",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 177, defaultShotCount: 2),
                        SizeInfo(name: "Large", caffeineAmount: 265, defaultShotCount: 3)]),
    Beverage(name: "카라멜 마끼아또",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 177, defaultShotCount: 2),
                        SizeInfo(name: "Large", caffeineAmount: 265, defaultShotCount: 3)]),
    Beverage(name: "바닐라 카페라떼",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 177, defaultShotCount: 2),
                        SizeInfo(name: "Large", caffeineAmount: 265, defaultShotCount: 3)]),
    Beverage(name: "카페 모카",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 197, defaultShotCount: 2),
                        SizeInfo(name: "Large", caffeineAmount: 295, defaultShotCount: 3)]),
    Beverage(name: "카푸치노",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 177, defaultShotCount: 2),
                        SizeInfo(name: "Large", caffeineAmount: 265, defaultShotCount: 3)]),
    Beverage(name: "숏 카페라떼",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 177, defaultShotCount: 2),
                        SizeInfo(name: "Large", caffeineAmount: 265, defaultShotCount: 3)]),
    Beverage(name: "아메리카노",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 177, defaultShotCount: 2),
                        SizeInfo(name: "Large", caffeineAmount: 265, defaultShotCount: 3)]),
    Beverage(name: "롱블랙",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 177, defaultShotCount: 2),
                        SizeInfo(name: "Large", caffeineAmount: 265, defaultShotCount: 3)]),
    Beverage(name: "에스프레소",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 89, defaultShotCount: 1),
                        SizeInfo(name: "Large", caffeineAmount: 177, defaultShotCount: 2)]),
    Beverage(name: "에스프레소 콘 파나",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 89, defaultShotCount: 1),
                        SizeInfo(name: "Large", caffeineAmount: 177, defaultShotCount: 2)]),
    Beverage(name: "에스프레소 마키아또",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 89, defaultShotCount: 1),
                        SizeInfo(name: "Large", caffeineAmount: 177, defaultShotCount: 2)]),
    Beverage(name: "아이스크림 카페라떼",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 177, defaultShotCount: 2),
                        SizeInfo(name: "Large", caffeineAmount: 265, defaultShotCount: 3)]),
    Beverage(name: "콜드브루",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 196, defaultShotCount: 0),
                        SizeInfo(name: "Large", caffeineAmount: 258, defaultShotCount: 0)]),
    Beverage(name: "콜드브루 라떼",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 196, defaultShotCount: 0),
                        SizeInfo(name: "Large", caffeineAmount: 258, defaultShotCount: 0)]),
    Beverage(name: "프렌치 얼그레이",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Large", caffeineAmount: 62, defaultShotCount: 0)]),
    Beverage(name: "그나와 민트티",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Large", caffeineAmount: 30, defaultShotCount: 0)]),
    Beverage(name: "잉글리쉬 브렉퍼스트",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Large", caffeineAmount: 59, defaultShotCount: 0)]),
    Beverage(name: "허니 레몬티",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 48, defaultShotCount: 0)]),
    Beverage(name: "애플 민트티",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 30, defaultShotCount: 0)]),
    Beverage(name: "로얄 밀크티",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 101, defaultShotCount: 0),
                        SizeInfo(name: "Large", caffeineAmount: 133, defaultShotCount: 0)]),
    Beverage(name: "그린티 라떼",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 55, defaultShotCount: 0),
                        SizeInfo(name: "Large", caffeineAmount: 68, defaultShotCount: 0)]),
    Beverage(name: "아이스 로얄 밀크티",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 128, defaultShotCount: 0),
                        SizeInfo(name: "Large", caffeineAmount: 171, defaultShotCount: 0)]),
    Beverage(name: "아이스 크린티 라떼",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 53, defaultShotCount: 0),
                        SizeInfo(name: "Large", caffeineAmount: 69, defaultShotCount: 0)]),
    Beverage(name: "바닐라 아포가토",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 89, defaultShotCount: 0)]),
    Beverage(name: "제주 말차 프라페",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 106, defaultShotCount: 0),
                        SizeInfo(name: "Large", caffeineAmount: 135, defaultShotCount: 0)]),
    Beverage(name: "모카칩 커피 프라페",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 270, defaultShotCount: 2),
                        SizeInfo(name: "Large", caffeineAmount: 307, defaultShotCount: 3)]),
    Beverage(name: "카라멜 커피 프라페",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 284, defaultShotCount: 2),
                        SizeInfo(name: "Large", caffeineAmount: 353, defaultShotCount: 3)]),
    Beverage(name: "로얄 밀크티 쉐이크",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 84, defaultShotCount: 0),
                        SizeInfo(name: "Large", caffeineAmount: 110, defaultShotCount: 0)]),
    Beverage(name: "초코 밀크 쉐이크",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 20, defaultShotCount: 0)]),
    Beverage(name: "커피 밀크 쉐이크",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 182, defaultShotCount: 2)]),
    Beverage(name: "초콜릿 라떼",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 16, defaultShotCount: 0),
                        SizeInfo(name: "Large", caffeineAmount: 21, defaultShotCount: 0)]),
    Beverage(name: "흑임자 카페라떼",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 177, defaultShotCount: 2),
                        SizeInfo(name: "Large", caffeineAmount: 265, defaultShotCount: 3)]),
    Beverage(name: "달고나 카페라떼",
             franchise: Franchise.twosomePlace,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 50, defaultShotCount: 0),
                        SizeInfo(name: "Large", caffeineAmount: 60, defaultShotCount: 0)])
]

let dummyEdiyaCoffeeBeverages: [Beverage] = [
    Beverage(name: "믹스라떼",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Extra", caffeineAmount: 270, defaultShotCount: 0)]),
    Beverage(name: "크림샷 라떼",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 93, defaultShotCount: 1)]),
    Beverage(name: "카페 아메리카노",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 91, defaultShotCount: 1),
                        SizeInfo(name: "Extra", caffeineAmount: 182, defaultShotCount: 2)]),
    Beverage(name: "카페 라떼",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 91, defaultShotCount: 1),
                        SizeInfo(name: "Extra", caffeineAmount: 182, defaultShotCount: 2)]),
    Beverage(name: "더블 토피넛 위드샷",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 96, defaultShotCount: 1)]),
    Beverage(name: "카페 모카",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 99, defaultShotCount: 1),
                        SizeInfo(name: "Extra", caffeineAmount: 197, defaultShotCount: 2)]),
    Beverage(name: "바닐라 라떼",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 103, defaultShotCount: 1),
                        SizeInfo(name: "Extra", caffeineAmount: 206, defaultShotCount: 2)]),
    Beverage(name: "아인슈페너",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 103, defaultShotCount: 1)]),
    Beverage(name: "연유 카페라떼",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 91, defaultShotCount: 1),
                        SizeInfo(name: "Extra", caffeineAmount: 206, defaultShotCount: 2)]),
    Beverage(name: "카푸치노",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 91, defaultShotCount: 1)]),
    Beverage(name: "카라멜 마끼아또",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 91, defaultShotCount: 1),
                        SizeInfo(name: "Extra", caffeineAmount: 182, defaultShotCount: 2)]),
    Beverage(name: "화이트 초콜릿 모카",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 91, defaultShotCount: 1),
                        SizeInfo(name: "Extra", caffeineAmount: 206, defaultShotCount: 2)]),
    Beverage(name: "민트 모카",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 113, defaultShotCount: 1)]),
    Beverage(name: "에스프레소",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 91, defaultShotCount: 1)]),
    Beverage(name: "연유 콜드브루",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 130, defaultShotCount: 0),
                        SizeInfo(name: "Extra", caffeineAmount: 195, defaultShotCount: 0)]),
    Beverage(name: "콜드브루 크림넛",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 130, defaultShotCount: 0)]),
    Beverage(name: "흑당 콜드브루",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 65, defaultShotCount: 0),
                        SizeInfo(name: "Extra", caffeineAmount: 130, defaultShotCount: 0)]),
    Beverage(name: "콜드브루 아메리카노",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 74, defaultShotCount: 0),
                        SizeInfo(name: "Extra", caffeineAmount: 195, defaultShotCount: 0)]),
    Beverage(name: "콜드브루 라떼",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 140, defaultShotCount: 0),
                        SizeInfo(name: "Extra", caffeineAmount: 195, defaultShotCount: 0)]),
    Beverage(name: "콜드브루 화이트비엔나",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 65, defaultShotCount: 0)]),
    Beverage(name: "콜드브루 니트로",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 170, defaultShotCount: 0)]),
    Beverage(name: "버블믹스라떼",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 270, defaultShotCount: 0)]),
    Beverage(name: "버블 흑당 콜드브루",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 65, defaultShotCount: 0),
                        SizeInfo(name: "Extra", caffeineAmount: 130, defaultShotCount: 0)]),
    Beverage(name: "달고나 믹스치노",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 230, defaultShotCount: 0),
                        SizeInfo(name: "Extra", caffeineAmount: 295, defaultShotCount: 0)]),
    Beverage(name: "커피 플랫치노",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 91, defaultShotCount: 1)]),
    Beverage(name: "모카 플랫치노",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 95, defaultShotCount: 1)]),
    Beverage(name: "카라멜 플랫치노",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 91, defaultShotCount: 1)]),
    Beverage(name: "녹차 플랫치노",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 43, defaultShotCount: 0)]),
    Beverage(name: "초콜릿 칩 플랫치노",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 45, defaultShotCount: 0)]),
    Beverage(name: "민트 초콜릿 칩 플랫치노",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 44, defaultShotCount: 0)]),
    Beverage(name: "아포가토 오리지널",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 91, defaultShotCount: 1)]),
    Beverage(name: "프레시그린티",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 27, defaultShotCount: 0)]),
    Beverage(name: "피치얼그레이",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 49, defaultShotCount: 0)]),
    Beverage(name: "프레시그린티",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 27, defaultShotCount: 0)]),
    Beverage(name: "밀크티",
             franchise: Franchise.ediyaCoffee,
             sizeInfo: [SizeInfo(name: "Regular", caffeineAmount: 35, defaultShotCount: 0)]),
]

let day: Double = 24 * 60 * 60

let dummyIntakeRecords = [
    IntakeRecord(date: Date(timeIntervalSinceNow: day * -30),
                 beverage: dummyBeverages[0],
                 size: SizeInfo(name: "Tall",
                                caffeineAmount: 100,
                                defaultShotCount: 2),
                 addedShotCount: 2),
    IntakeRecord(date: Date(timeIntervalSinceNow: day * -10),
                 beverage: dummyBeverages[0],
                 size: SizeInfo(name: "Tall",
                                caffeineAmount: 100,
                                defaultShotCount: 2),
                 addedShotCount: 2),
    IntakeRecord(date: Date(timeIntervalSinceNow: day * -10),
                 beverage: dummyBeverages[0],
                 size: SizeInfo(name: "Tall",
                                caffeineAmount: 100,
                                defaultShotCount: 2),
                 addedShotCount: 2),
    IntakeRecord(date: Date(timeIntervalSinceNow: day * -8),
                 beverage: dummyBeverages[0],
                 size: SizeInfo(name: "Tall",
                                caffeineAmount: 100,
                                defaultShotCount: 2),
                 addedShotCount: 2),
    IntakeRecord(date: Date(timeIntervalSinceNow: day * -7),
                 beverage: dummyBeverages[0],
                 size: SizeInfo(name: "Tall",
                                caffeineAmount: 100,
                                defaultShotCount: 2),
                 addedShotCount: 2),
    IntakeRecord(date: Date(timeIntervalSinceNow: day * -6),
                 beverage: dummyBeverages[0],
                 size: SizeInfo(name: "Tall",
                                caffeineAmount: 100,
                                defaultShotCount: 2),
                 addedShotCount: 2),
    IntakeRecord(date: Date(timeIntervalSinceNow: day * -5),
                 beverage: dummyBeverages[0],
                 size: SizeInfo(name: "Tall",
                                caffeineAmount: 100,
                                defaultShotCount: 2),
                 addedShotCount: 2),
    IntakeRecord(date: Date(timeIntervalSinceNow: day * -4),
                 beverage: dummyBeverages[0],
                 size: SizeInfo(name: "Tall",
                                caffeineAmount: 100,
                                defaultShotCount: 2),
                 addedShotCount: 2),
    IntakeRecord(date: Date(timeIntervalSinceNow: day * -3),
                 beverage: dummyBeverages[0],
                 size: SizeInfo(name: "Tall",
                                caffeineAmount: 100,
                                defaultShotCount: 2),
                 addedShotCount: 2),
    IntakeRecord(date: Date(timeIntervalSinceNow: day * -2),
                 beverage: dummyBeverages[0],
                 size: SizeInfo(name: "Tall",
                                caffeineAmount: 100,
                                defaultShotCount: 2),
                 addedShotCount: 2),
    IntakeRecord(date: Date(timeIntervalSinceNow: day * -1),
                 beverage: dummyBeverages[0],
                 size: SizeInfo(name: "Tall",
                                caffeineAmount: 100,
                                defaultShotCount: 2),
                 addedShotCount: 2),
    IntakeRecord(date: Date(timeIntervalSinceNow: 0),
                 beverage: dummyBeverages[0],
                 size: SizeInfo(name: "Tall",
                                caffeineAmount: 100,
                                defaultShotCount: 2),
                 addedShotCount: 2),
]
