//
//  DummyData.swift
//  Techome
//
//  Created by Yeongwoo Kim on 2022/06/09.
//

import Foundation

let drinkDatas: [DrinkData] = [
    DrinkData(name: "스타벅스 돌체 라떼",
              franchise: Franchise.starbucks,
              caffeineAmount: [150, 225, 300],
              defaultShotCount: [2, 3, 4]),
    DrinkData(name: "카페 모카",
              franchise: Franchise.starbucks,
              caffeineAmount: [95, 175, 180],
              defaultShotCount: [1, 2, 2]),
    DrinkData(name: "카페 아메리카노",
              franchise: Franchise.starbucks,
              caffeineAmount: [150, 225, 300],
              defaultShotCount: [2, 3, 4]),
    DrinkData(name: "카페 라떼",
              franchise: Franchise.starbucks,
              caffeineAmount: [75, 150, 150],
              defaultShotCount: [1, 2, 2]),
    DrinkData(name: "카푸치노",
              franchise: Franchise.starbucks,
              caffeineAmount: [75, 150, 150],
              defaultShotCount: [1, 2, 2]),
    DrinkData(name: "카라멜 마끼아또",
              franchise: Franchise.starbucks,
              caffeineAmount: [75, 150, 150],
              defaultShotCount: [1, 2, 2]),
    DrinkData(name: "화이트 초콜릿 모카",
              franchise: Franchise.starbucks,
              caffeineAmount: [75, 150, 150],
              defaultShotCount: [1, 2, 2]),
    DrinkData(name: "더블 에스프레소 칩 프라푸치노",
              franchise: Franchise.starbucks,
              caffeineAmount: [130, 130, 260],
              defaultShotCount: [2, 2, 4]),
    DrinkData(name: "제주 유기농 말차로 만든 크림 프라푸치노",
              franchise: Franchise.starbucks,
              caffeineAmount: [60, 90, 120],
              defaultShotCount: [2, 3, 4]),
    DrinkData(name: "자바 칩 프라푸치노",
              franchise: Franchise.starbucks,
              caffeineAmount: [100, 130, 180],
              defaultShotCount: [2, 3, 4]),
    DrinkData(name: "화이트 초콜릿 모카 프라푸치노",
              franchise: Franchise.starbucks,
              caffeineAmount: [85, 110, 155],
              defaultShotCount: [1, 2, 3]),
    DrinkData(name: "모카 프라푸치노",
              franchise: Franchise.starbucks,
              caffeineAmount: [90, 115, 165],
              defaultShotCount: [1, 2, 3]),
    DrinkData(name: "화이트 초콜릿 모카 프라푸치노",
              franchise: Franchise.starbucks,
              caffeineAmount: [85, 110, 155],
              defaultShotCount: [1, 2, 3]),
    DrinkData(name: "카라멜 프라푸치노",
              franchise: Franchise.starbucks,
              caffeineAmount: [85, 110, 155],
              defaultShotCount: [1, 2, 3]),
    DrinkData(name: "에스프레소 프라푸치노",
              franchise: Franchise.starbucks,
              caffeineAmount: [120, 155, 155],
              defaultShotCount: [3, 4, 4]),
    DrinkData(name: "카라멜 프라푸치노",
              franchise: Franchise.starbucks,
              caffeineAmount: [85, 110, 155],
              defaultShotCount: [1, 2, 3]),
    DrinkData(name: "돌체 블랙 밀크 티",
              franchise: Franchise.starbucks,
              caffeineAmount: [35, 45, 55],
              defaultShotCount: [3, 4, 5]),
    DrinkData(name: "제주 유기농 말차로 만든 라떼",
              franchise: Franchise.starbucks,
              caffeineAmount: [60, 90, 120],
              defaultShotCount: [2, 3, 4]),
    DrinkData(name: "차이 티 라떼",
              franchise: Franchise.starbucks,
              caffeineAmount: [70, 95, 115],
              defaultShotCount: [3, 4, 5]),
    DrinkData(name: "자몽 허니 블랙 티",
              franchise: Franchise.starbucks,
              caffeineAmount: [70, 95, 150],
              defaultShotCount: [1, 2, 3]),
    DrinkData(name: "잉글리시 브렉퍼스트 티",
              franchise: Franchise.starbucks,
              caffeineAmount: [70, 0, 150],
              defaultShotCount: [1, 0, 2]),
    DrinkData(name: "얼 그레이 티",
              franchise: Franchise.starbucks,
              caffeineAmount: [70, 0, 120],
              defaultShotCount: [1, 0, 2]),
    DrinkData(name: "오늘의 커피",
              franchise: Franchise.starbucks,
              caffeineAmount: [260, 330, 415],
              defaultShotCount: [2, 3, 4]),
    DrinkData(name: "아이스 커피",
              franchise: Franchise.starbucks,
              caffeineAmount: [140, 190, 220],
              defaultShotCount: [2, 3, 4]),
]
