////
////  DummyData.swift
////  Techome
////
////  Created by Yeongwoo Kim on 2022/06/09.
////
//
//import Foundation
//
//let beverageDatas: [Beverage] = [
//    Beverage(name: "스타벅스 돌체 라떼",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 150,
//             defaultShotCount: 2),
//    Beverage(name: "스타벅스 돌체 라떼",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 225,
//             defaultShotCount: 3),
//    Beverage(name: "스타벅스 돌체 라떼",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 300,
//             defaultShotCount: 4),
//
//    Beverage(name: "카페 모카",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 95,
//             defaultShotCount: 1),
//    Beverage(name: "카페 모카",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 175,
//             defaultShotCount: 2),
//    Beverage(name: "카페 모카",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 180,
//             defaultShotCount: 2),
//
//    Beverage(name: "카페 아메리카노",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 150,
//             defaultShotCount: 2),
//    Beverage(name: "카페 아메리카노",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 225,
//             defaultShotCount: 3),
//    Beverage(name: "카페 아메리카노",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 300,
//             defaultShotCount: 4),
//
//    Beverage(name: "카페 라떼",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 75,
//             defaultShotCount: 1),
//    Beverage(name: "카페 라떼",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 150,
//             defaultShotCount: 2),
//    Beverage(name: "카페 라떼",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 150,
//             defaultShotCount: 2),
//
//    Beverage(name: "카푸치노",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 75,
//             defaultShotCount: 1),
//    Beverage(name: "카푸치노",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 150,
//             defaultShotCount: 2),
//    Beverage(name: "카푸치노",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 150,
//             defaultShotCount: 2),
//
//    Beverage(name: "카라멜 마끼아또",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 75,
//             defaultShotCount: 1),
//    Beverage(name: "카라멜 마끼아또",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 150,
//             defaultShotCount: 2),
//    Beverage(name: "카라멜 마끼아또",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 150,
//             defaultShotCount: 2),
//
//    Beverage(name: "화이트 초콜릿 모카",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 75,
//             defaultShotCount: 1),
//    Beverage(name: "화이트 초콜릿 모카",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 150,
//             defaultShotCount: 2),
//    Beverage(name: "화이트 초콜릿 모카",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 150,
//             defaultShotCount: 2),
//
//    Beverage(name: "더블 에스프레소 칩 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 130,
//             defaultShotCount: 2),
//    Beverage(name: "더블 에스프레소 칩 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 130,
//             defaultShotCount: 2),
//    Beverage(name: "더블 에스프레소 칩 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 130,
//             defaultShotCount: 4),
//
//    Beverage(name: "제주 유기농 말차로 만든 크림 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 60,
//             defaultShotCount: 0),
//    Beverage(name: "제주 유기농 말차로 만든 크림 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 90,
//             defaultShotCount: 0),
//    Beverage(name: "제주 유기농 말차로 만든 크림 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 120,
//             defaultShotCount: 0),
//
//    Beverage(name: "자바 칩 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 100,
//             defaultShotCount: 0),
//    Beverage(name: "자바 칩 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 130,
//             defaultShotCount: 0),
//    Beverage(name: "자바 칩 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 180,
//             defaultShotCount: 0),
//
//    Beverage(name: "화이트 초콜릿 모카 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 85,
//             defaultShotCount: 0),
//    Beverage(name: "화이트 초콜릿 모카 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 110,
//             defaultShotCount: 0),
//    Beverage(name: "화이트 초콜릿 모카 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 155,
//             defaultShotCount: 0),
//
//    Beverage(name: "모카 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 90,
//             defaultShotCount: 0),
//    Beverage(name: "모카 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 115,
//             defaultShotCount: 0),
//    Beverage(name: "모카 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 165,
//             defaultShotCount: 0),
//
//
//    Beverage(name: "에스프레소 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 120,
//             defaultShotCount: 1),
//    Beverage(name: "에스프레소 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 155,
//             defaultShotCount: 1),
//    Beverage(name: "에스프레소 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 155,
//             defaultShotCount: 1),
//
//    Beverage(name: "카라멜 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 85,
//             defaultShotCount: 0),
//    Beverage(name: "카라멜 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 110,
//             defaultShotCount: 0),
//    Beverage(name: "카라멜 프라푸치노",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 155,
//             defaultShotCount: 0),
//
//    Beverage(name: "돌체 블랙 밀크 티",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 35,
//             defaultShotCount: 0),
//    Beverage(name: "돌체 블랙 밀크 티",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 45,
//             defaultShotCount: 0),
//    Beverage(name: "돌체 블랙 밀크 티",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 55,
//             defaultShotCount: 0),
//
//    Beverage(name: "제주 유기농 말차로 만든 라떼",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 60,
//             defaultShotCount: 0),
//    Beverage(name: "제주 유기농 말차로 만든 라떼",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 90,
//             defaultShotCount: 0),
//    Beverage(name: "제주 유기농 말차로 만든 라떼",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 120,
//             defaultShotCount: 0),
//
//    Beverage(name: "차이 티 라떼",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 70,
//             defaultShotCount: 0),
//    Beverage(name: "차이 티 라떼",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 95,
//             defaultShotCount: 0),
//    Beverage(name: "차이 티 라떼",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 115,
//             defaultShotCount: 0),
//
//    Beverage(name: "자몽 허니 블랙 티",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 30,
//             defaultShotCount: 0),
//    Beverage(name: "자몽 허니 블랙 티",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 45,
//             defaultShotCount: 0),
//    Beverage(name: "자몽 허니 블랙 티",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 55,
//             defaultShotCount: 0),
//
//    Beverage(name: "잉글리시 브렉퍼스트 티",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 70,
//             defaultShotCount: 0),
//    Beverage(name: "잉글리시 브렉퍼스트 티",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 150,
//             defaultShotCount: 0),
//
//    Beverage(name: "얼 그레이 티",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 70,
//             defaultShotCount: 0),
//    Beverage(name: "얼 그레이 티",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 120,
//             defaultShotCount: 0),
//
//    Beverage(name: "오늘의 커피",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 260,
//             defaultShotCount: 0),
//    Beverage(name: "오늘의 커피",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 330,
//             defaultShotCount: 0),
//    Beverage(name: "오늘의 커피",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 415,
//             defaultShotCount: 0),
//
//    Beverage(name: "아이스 커피",
//             franchise: Franchise.starbucks,
//             size: "Tall",
//             caffeineAmount: 140,
//             defaultShotCount: 0),
//    Beverage(name: "아이스 커피",
//             franchise: Franchise.starbucks,
//             size: "Grande",
//             caffeineAmount: 190,
//             defaultShotCount: 0),
//    Beverage(name: "아이스 커피",
//             franchise: Franchise.starbucks,
//             size: "Venti",
//             caffeineAmount: 220,
//             defaultShotCount: 0),
//]
